### ISSUE TITLE
Image Size Optimization

### ISSUE THREAD

**Issue by eabili0** [flaviostutz/etcd-registrar#1]
Hello @flaviostutz,

I have a containerized Node.js application that needs to register itself to an ETCD instance to perform the lifecycle proposed by [flaviostutz/promster](https://github.com/flaviostutz/promster) for application monitoring.

The best way I can see to use [etcd-registrar](https://github.com/flaviostutz/etcd-registrar), is by multistage build my docker image. But, I feel that the default image for this project is a little too big and can impact the performance of my CI/CD setup. I also feel this image can be further optimized (by adopting alpine, maybe?).

Can I proceed with a PR that accomplishes just that? Thanks in advance!

**Comment by flaviostutz** [comment]
Sure! It would be great!
